stages:
  - build

build_and_push:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
    DOCKER_CLI_EXPERIMENTAL: "enabled"
  before_script:
    # 登录 Docker Hub
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker buildx version
    - docker buildx create --use
  script:
    # 构造 tag
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        export IMAGE_TAG="$CI_COMMIT_TAG"
      else
        export IMAGE_TAG="latest"
      fi
    # 构建并推送镜像
    - docker buildx build --platform linux/amd64 -t $DOCKERHUB_USERNAME/bee-icp-server:$IMAGE_TAG --push .
    # 如果是 tag，还推送 latest（可选）
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        docker buildx build --platform linux/amd64 -t $DOCKERHUB_USERNAME/bee-icp-server:latest --push .
      fi
  only:
    - main
    - tags