version: '3.8'

services:
  # MySQL数据库服务 - 生产环境配置
  mysql:
    image: mysql:8.0
    container_name: icp-mysql-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-icp_database}
      MYSQL_USER: ${MYSQL_USER:-icp_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./deployment/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./deployment/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - icp-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ICP应用服务 - 生产环境配置
  icp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: icp-app-prod
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://${MYSQL_USER:-icp_user}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE:-icp_database}
      HOST: 0.0.0.0
      PORT: 8600
      DEBUG: false
      CHINAZ_API_KEY: ${CHINAZ_API_KEY}
      TIANYANCHA_API_KEY: ${TIANYANCHA_API_KEY}
      API_KEY: ${API_KEY}
      CACHE_EXPIRE_DAYS: ${CACHE_EXPIRE_DAYS:-30}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - icp-network
    volumes:
      - /data/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8600/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Nginx反向代理服务 - 生产环境配置
  nginx:
    image: nginx:alpine
    container_name: icp-nginx-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./deployment/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./deployment/nginx/ssl:/etc/nginx/ssl:ro
      - /data/logs/nginx:/var/log/nginx
    depends_on:
      - icp-app
    networks:
      - icp-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  icp-network:
    driver: bridge