version: '3.8'

services:
  # MySQL数据库服务
  mysql:
    image: mysql:8.0
    container_name: icp-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-icp_database}
      MYSQL_USER: ${MYSQL_USER:-icp_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-icp_password}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./deployment/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - icp-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # ICP应用服务
  icp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: icp-app
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql+pymysql://${MYSQL_USER:-icp_user}:${MYSQL_PASSWORD:-icp_password}@mysql:3306/${MYSQL_DATABASE:-icp_database}
      HOST: 0.0.0.0
      PORT: 8600
      DEBUG: ${DEBUG:-false}
      CHINAZ_API_KEY: ${CHINAZ_API_KEY}
      TIANYANCHA_API_KEY: ${TIANYANCHA_API_KEY}
      API_KEY: ${API_KEY:-your-secret-api-key}
      CACHE_EXPIRE_DAYS: ${CACHE_EXPIRE_DAYS:-30}
    ports:
      - "${APP_PORT:-8600}:8600"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - icp-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8600/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx反向代理服务
  nginx:
    image: nginx:alpine
    container_name: icp-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployment/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./deployment/nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - icp-app
    networks:
      - icp-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local

networks:
  icp-network:
    driver: bridge