version: '3'

services:
  # MySQL数据库服务 - 生产环境配置
  mysql:
    image: mysql:8.0
    container_name: icp-mysql-prod
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-icp_database}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      TZ: Asia/Shanghai
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--transaction-isolation=READ-COMMITTED', '--innodb_log_file_size=256M', '--max_allowed_packet=256M','--log_bin_trust_function_creators=1']
    volumes:
      - ./data/mysql/mysql:/var/lib/mysql
      - ./deployment/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./deployment/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    privileged: true # 避免权限不足导致mysql启动失败
    networks:
      - icp-network

  # ICP应用服务 - 生产环境配置
  icp-app:
    image: diudiudiuuuu/bee-icp-server:v1.0.0
    container_name: icp-app-prod
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DATABASE:-icp_database}
      HOST: 0.0.0.0
      PORT: ${APP_PORT}
      DEBUG: ${DEBUG}
      CHINAZ_API_KEY: ${CHINAZ_API_KEY}
      TIANYANCHA_API_KEY: ${TIANYANCHA_API_KEY}
      API_KEY: ${API_KEY}
      CACHE_EXPIRE_DAYS: ${CACHE_EXPIRE_DAYS:-30}
    depends_on:
      - mysql
    networks:
      - icp-network
    volumes:
      - ./data/icp-app/logs:/app/logs

  # Nginx反向代理服务 - 生产环境配置
  nginx:
    image: nginx:alpine
    container_name: icp-nginx-prod
    restart: always
    ports:
      - "48033:80"
    volumes:
      - ./deployment/nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./deployment/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./deployment/nginx/ssl:/etc/nginx/ssl:ro
      - ./data/nginx/logs:/var/log/nginx
    depends_on:
      - icp-app
    networks:
      - icp-network

networks:
  icp-network:
    driver: bridge