"""Add is_historical field to ICPRecord

Revision ID: ab6ca2a1bf9c
Revises: 
Create Date: 2025-09-19 18:48:31.608596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6ca2a1bf9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icp_records', sa.Column('is_historical', sa.Boolean(), nullable=False, comment='是否为历史备案'))
    op.create_index('idx_is_historical', 'icp_records', ['is_historical'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_is_historical', table_name='icp_records')
    op.drop_column('icp_records', 'is_historical')
    # ### end Alembic commands ###
