name: Build and Push Docker Image

on:
  push:
    branches: [main]
    tags: ["v*"] # 只对以 v 开头的 tag 触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set Docker image tags
        id: vars
        run: |
          # 提取 tag 名称，去掉 refs/tags/ 前缀
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION_TAG="${GITHUB_REF#refs/tags/}"
            TAGS="${{ secrets.DOCKERHUB_USERNAME }}/bee-icp-server:latest,${{ secrets.DOCKERHUB_USERNAME }}/bee-icp-server:${VERSION_TAG}"
          else
            TAGS="${{ secrets.DOCKERHUB_USERNAME }}/bee-icp-server:latest"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.tags }}